r1880@pythagoras (orig r1879):  dvs | 2008-06-16 16:09:31 +0200  Cleanup of deprecated stage3 stuff (libpci, hwsetup, ...) and update to  new functions (init, hwautocfg, servconfig, ...)

diff --git a/openslx/branches/initramfs-ng/etc/functions b/openslx/branches/initramfs-ng/etc/functions
--- a/openslx/branches/initramfs-ng/etc/functions
+++ b/openslx/branches/initramfs-ng/etc/functions
@@ -93,12 +93,6 @@ else
   rest="$var"
   prot=""
 fi
-# remove temporary '::' from path, since it conflicts with port specification
-if strinstr "::" "$rest" ; then
-  rest=$(echo $rest | sed -e 's,::,§§§§§,g')
-elif strinstr "\:\:" "$rest" ; then
-  rest=$(echo $rest | sed -e 's,\:\:,§§§§§,g')
-fi
 # get the server IP or name and port - URI authority
 # you get the path or other token without leading "/" - add it later if
 # needed (fixme: port might be broken)
@@ -123,31 +117,43 @@ fi
 case "$2" in
   prot) echo "$prot" ;;
   server) echo "$server" ;;
-  # add '::' again to path
-  path) echo "$path" | sed -e 's,§§§§§,\:\:,g' ;;
+  path) echo "$path" ;;
   port) echo "$port" ;;
   query) echo "$query" ;;
 esac
 }
 #############################################################################
-# compute prefix bit number from netmask
-nm2pref () {
-set $(IFS="."; echo $1)
-local n=0
-local i
-  for i in $1 $2 $3 $4 ; do
-    case $i in
-        0) break ;;
-      128) n=$(($n + 1)) ; break ;;
-      192) n=$(($n + 2)) ; break ;;
-      224) n=$(($n + 3)) ; break ;;
-      240) n=$(($n + 4)) ; break ;;
-      252) n=$(($n + 6)) ; break ;;
-      254) n=$(($n + 7)) ; break ;;
-      255) n=$(($n + 8)) ; continue ;;
-    esac
-  done
-echo $n
+# load the kernel nfs module if not compiled in
+nfsmod () {
+if cat /proc/filesystems | grep -i nfs >/dev/null 2>&1 ; then
+  modprobe ${MODPRV} 2>/dev/null || error "$error_nfsmod" nonfatal
+fi
+}
+#############################################################################
+# configure Xen bridge xenbr0
+xenbr_config () {
+modprobe ${MODPRV} netloop
+local ipls
+local vifnum="0"
+local bridge="xenbr${vifnum}"
+local netdev="eth${vifnum}"
+local pdev="p${netdev}"
+local vdev="veth${vifnum}"
+local vif0="vif0.${vifnum}"
+# fixme: that is the mac address of main ethernet device
+local mac=$macaddr
+
+brctl addbr ${bridge}
+brctl stp ${bridge} off
+brctl setfd ${bridge} 0
+brctl addif ${bridge} ${vif0}
+for ipls in "${netdev} name ${pdev}" "${vdev} name ${netdev}" \
+            "${pdev} down arp off" "${pdev} addr fe:ff:ff:ff:ff:ff" \
+            "${netdev} addr ${mac} arp on" "${netdev} addr ${mac} arp on" \
+            "${bridge} up" "${vif0} up" "${pdev} up" ; do
+  ip link set ${ipls}
+done
+brctl addif ${bridge} ${pdev}
 }
 #############################################################################
 # replace @@@serverip@@@ with real serverip. Allows the usage of a variable
@@ -244,72 +250,24 @@ for fs in xfs ext2 reiserfs ; do
   fi
 done
 }
-#############################################################################
-# create configuration file for dhclient
-mkdhclconf () {
-local vci=$1
-# provide dhclient with proper configuration
-echo -e "option bootlocal-script code 221\t= string;\n\
-option language code 222\t\t= string;\n\
-option start-x code 223\t\t\t= string;\n\
-option start-snmp code 224\t\t= string;\n\
-option start-sshd code 225\t\t= string;\n\
-option start-xdmcp code 226\t\t= string;\n\
-option start-cron code 227\t\t= string;\n\
-option crontab-entries code 228\t\t= string;\n\
-option start-rwhod code 229\t\t= string;\n\
-option start-printdaemon code 230\t= string;\n\
-option desktop-session code 231\t\t= string;\n\
-option tex-enable code 232\t\t= string;\n\
-option netbios-workgroup code 233\t= string;\n\
-option vmware code 234\t\t\t= string;\n\
-option hw-mouse code 252\t\t= string;\n\
-option hw-graphic code 253\t\t= string;\n\
-option hw-monitor code 254\t\t= string;\n\n\
-send dhcp-lease-time 86400;\nsend dhcp-max-message-size 1400;\n\
-request;\nscript \"/bin/dhclient-script\";" >> /etc/dhclient.conf
-if [ -n "$vci" ] ; then
-  echo "send vendor-class-identifier \"$vci\";" >> /etc/dhclient.conf
-fi
-}
 
 #############################################################################
-# dhcp client function (supporting dhclient and udhcp, latter is preferred)
+# dhcp client function
 rundhcp ()
 {
 local vci="$1"
-for dhcp in dhclient udhcpc none; do
-  test -e /bin/$dhcp && break;
-done
-if [ "$dhcp" = "none" ] ; then
-  error "$error_nodhcp" nonfatal
-else
-  # ensure the interface is up - might produce conflicts - nbd could
-  # fail!!
-  [ -n "$noipyet" ] && \
-    ip link set dev $nwif up
-  [ -f /lib/modules/@@@KERNVER@@@/kernel/net/packet/af_packet.ko ] && \
-    modprobe ${MODPRV} af_packet   
-  echo "Starting $dhcp for configuration"
-  mkdir /var/lib/dhcp >/dev/null 2>&1
-fi
-export client="$dhcp"
-case $dhcp in
-  dhclient)
-    mkdhclconf $vci
-    ln -s /bin/dhcpmkconfig /bin/dhclient-script
-    dhclient -cf /etc/dhclient.conf -lf /var/lib/dhcp/dhclient.leases \
-      -q $nwif >/dev/null 2>&1 || error "$error_dhclient"
-  ;;
-  # udhcpc is a busybox applet
-  udhcpc)
-    [ -n $vci ] && vci="-V $vci"
-    testmkd /usr/share/udhcpc
-    ln -s /bin/dhcpmkconfig /usr/share/udhcpc/default.script
-    # -b option is suboptimal here ...
-    udhcpc -t 8 -q $vci -s /usr/share/udhcpc/default.script -i $nwif 2>/dev/null
-  ;;
-esac
+# ensure the interface is up - might produce conflicts - nbd could fail!!
+# fixme: really needed?
+#  [ -n "$noipyet" ] && ip link set dev $nwif up
+[ -f /lib/modules/${KERNEL}/kernel/net/packet/af_packet.ko ] && \
+  modprobe ${MODPRV} af_packet   
+echo "Starting udhcpc for IP configuration"
+mkdir /var/lib/dhcp >/dev/null 2>&1
+[ -n $vci ] && vci="-V $vci"
+testmkd /usr/share/udhcpc
+ln -sf /bin/dhcpmkconfig /usr/share/udhcpc/default.script
+# -b option is suboptimal here ...
+udhcpc -t 8 -q $vci -s /usr/share/udhcpc/default.script -i $nwif 2>/dev/null
 echo "dhcp finished at $(sysup)" >/tmp/dhcp-done
 }
 
@@ -339,7 +297,7 @@ fileget () {
 local cfgfile
 [ "x$fileprot" = "x" ] && fileprot=tftp
 if [ "x$filepath" != "x" ] ; then
-  cfgfile="${filepath}"
+  cfgfile=${filepath}
   [ "x$fileserv" = "x" ] && fileserv=$(checkip ${serverip})
   case "$fileprot" in
    ftp|http)
@@ -353,12 +311,12 @@ if [ "x$filepath" != "x" ] ; then
      mkdir /tmp/$ldev
      echo -e "ext2\nreiserfs\nvfat\nxfs" >/etc/filesystems
      mount -o ro /dev/$ldev /tmp/$ldev || error "$init_errlfg"
-     unpack /tmp/$ldev/"$cfgfile"
+     unpack /tmp/$ldev/$cfgfile
      umount /dev/$ldev
    ;;
    *)
-     tftp -g -r "$cfgfile" -l /tmp/$(basename "$cfgfile") $fileserv  \
-       && unpack /tmp/$(basename "$cfgfile")
+     tftp -g -r $cfgfile -l /tmp/$(basename $cfgfile) $fileserv  \
+       && unpack /tmp/$(basename $cfgfile)
    ;;
    esac
 else
@@ -372,16 +330,16 @@ else
   echo -e "\n## Configuration via fileget: Hierarchy is distro client \
 and as last\n# distro/default" >> /tmp/confviafile
   mac=$(echo $macaddr|sed "s/:/-/g")
-  for cfgfile in "${filepath}/${SYSTEM_NAME}/01-${mac}.tgz" \
-                 "${filepath}/${SYSTEM_NAME}/default.tgz" ; do
+  for cfgfile in ${filepath}/${SYSTEM_NAME}/01-$mac.tgz \
+                 ${filepath}/${SYSTEM_NAME}/default.tgz ; do
     case "$fileprot" in
       ftp|http)
-        wget $fileprot://$fileserv/"$cfgfile" -O /tmp/$(basename "$cfgfile") \
-          2>/dev/null && { unpack /tmp/$(basename "$cfgfile") && break; }
+        wget $fileprot://$fileserv/$cfgfile -O /tmp/$(basename $cfgfile) \
+          2>/dev/null && { unpack /tmp/$(basename $cfgfile) && break; }
       ;;
       tftp)
-        tftp -g -r "$cfgfile" -l /tmp/$(basename "$cfgfile") $fileserv \
-           && { unpack /tmp/$(basename "$cfgfile") && break; }
+        tftp -g -r $cfgfile -l /tmp/$(basename $cfgfile) $fileserv \
+           && { unpack /tmp/$(basename $cfgfile) && break; }
       ;;
     esac
   done
@@ -854,7 +812,9 @@ include_in_fsroot_union () {
     srvproto=$(uri_token $ROOTFS prot)
     case $srvproto in
           nfs)
-            # nfsroot consists now of two different parts
+            # activate kernel nfs if not present, nfsroot consists now of two
+            # different parts
+            nfsmod
             root_path=$(uri_token $ROOTFS path)
             nfsserver=$(uri_token $ROOTFS server)
             mkdir -p /mnt/tmp/${root_path}_${union_id}
diff --git a/openslx/branches/initramfs-ng/init b/openslx/branches/initramfs-ng/init
--- a/openslx/branches/initramfs-ng/init
+++ b/openslx/branches/initramfs-ng/init
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/ash
 # Copyright (c) 2003 - 2006 - RZ Uni Freiburg
 # Copyright (c) 2006 - 2008 - OpenSLX GmbH
 #
@@ -14,9 +14,18 @@
 # clients version 4
 #############################################################################
 
+# fixme: shut down if script fails - this does not really work in case of
+# script crash
+trap "exec (sleep 30; echo o>/proc/sysrq-trigger)" \
+  SIGHUP SIGINT SIGPIPE SIGTERM
+
 # device files get their own filesystem (to be move mounted later)
 devdir="/dev"
 mount -n -t tmpfs -o 'size=25%,mode=0755' initramfsdevs ${devdir}
+
+# mount the important standard directories
+[ ! -f /proc/cpuinfo ] && mount -n -t proc proc /proc
+[ ! -d /sys/class ] && mount -n -t sysfs sysfs /sys
 
 # create basic device files an directories in dev (for most hardware related
 # devices mdev should handle that)
@@ -33,6 +42,10 @@ done
 mkdir -p ${devdir}/pts ${devdir}/shm ${devdir}/.udevdb ${devdir}/.udev \
   ${devdir}/.initramfs
 
+# start device auto discovery/setup service of busybox
+echo > /etc/mdev.conf
+mdev -s
+
 # source functions file common for all distros, messages contains all error
 # and info output (for some reason the error output is not produced properly
 # - crash)
@@ -43,12 +56,12 @@ mkdir -p ${devdir}/pts ${devdir}/shm ${devdir}/.udevdb ${devdir}/.udev \
 . /etc/distro-functions || ( echo -e $init_dff && sleep 100 )
 # distro specific configuration settings (several file and directory
 # variables)
-. /etc/sysconfig/config || ( echo -e $init_dscf && sleep 100 )
+. /etc/distro-config || ( echo -e $init_dscf && sleep 100 )
 # configuration settings for this slx system's environment
-. /etc/sysconfig/slxsystem.conf 2>/dev/null || ( echo -e ${init_sscf} && \
+. /etc/slxsystem.conf 2>/dev/null || ( echo -e ${init_sscf} && \
   sleep 100 )
 # initramfs-setup configuration (common settings for all clients using a
-# certain InitRamFS generated through slxconfig-demuxer)
+# certain InitRamFS generated by slxmkramfs/mkdxsinitrd)
 [ -f /etc/initramfs-setup ] && . /etc/initramfs-setup 2>/dev/null
 
 export PATH=/bin:/sbin:/usr/bin/:/usr/sbin
@@ -69,13 +82,10 @@ nodnbdcache="yes"
 # more than one ethernet card built in
 nwif="eth0"
 
-# mount the important standard directories
-[ ! -f /proc/cpuinfo ] && mount -n -t proc proc /proc
-[ ! -d /sys/class ] && mount -n -t sysfs sysfs /sys
-
-# fixme: shut down if script fails
-trap "exec (sleep 30; echo o>/proc/sysrq-trigger)" \
-  SIGHUP SIGINT SIGPIPE SIGTERM
+# load usb modules for keyboard (reenable usb keyboards, otherwise the
+# admin has to wait until second run of hwsetup late in stage3) and the
+# network adaptor modules, search for pci modules to load later on
+hwautocfg base
 
 # if no kernel version is set, try to get it directly from /proc
 if [ -z $KERNEL ] ; then
@@ -83,16 +93,13 @@ if [ -z $KERNEL ] ; then
   KERNEL=${KERNEL#*version }
   KERNEL=${KERNEL% (*) (*}
 fi
+
 # set defaults for some important variables, might be overwritten via
 # kernel commandline
 tmpfssize="50%"
 cowsize="50%"
 rwdir=/dev/shm
 nfsro="nfs"
-
-# load usb modules for keyboard (reenable usb keyboards, otherwise the
-# admin has to wait until second run of hwsetup late in stage3)
-hwautocfg pre
 
 runinithook '00-started'
 
@@ -101,9 +108,6 @@ runinithook '00-started'
 preinit
 [ -x /bin/preinit.local ] && /bin/preinit.local
 
-# start device auto discovery service of busybox
-echo > /etc/mdev.conf
-mdev -s
 
 # switch off the several configuration methods, will be switched on
 # according to kernel commandline settings
@@ -120,6 +124,10 @@ export KCMDLINE
 # read the system wide machine-setup and then the kernel commandline
 for opts in $(sed "s/#.*//" /etc/initramfs-setup) ${KCMDLINE} ; do
   case ${opts} in
+    # from IPAPPEND
+    BOOTIF=*)
+      bootmac=$(echo ${opts} | sed "s/.*=01-//;s/-/:/g")
+    ;;
     # localization
     country=*)
       COUNTRY=${opts#country=}
@@ -301,6 +309,7 @@ configuration to\n# your kernel command line." >> /etc/machine-setup
     error "$init_errip"
   fi
 fi
+
 # for ldap configuration at least basic IP setup is needed to contact the
 # server
 [ -n "$nodhcp" -a -n "$ldap" -a -z "$ipinfo" ] && error "$init_errldap"
@@ -330,11 +339,11 @@ else
   MODPRV="-q"
   LOGFILE="/dev/null"
   # redirect console (after /dev/null is available, and /dev mounted)
-  [ "${DEBUGLEVEL}" != 8 ] && exec < /dev/console > /dev/null 2>&1
+  #[ "${DEBUGLEVEL}" != 8 ] && exec < /dev/console > /dev/null 2>&1
 fi
-# load network adaptor modules, check for WLAN specific settings and check
-# for multiple ethernet interfaces (not implemented yet)
-hwautocfg nwmod
+
+# check for WLAN specific settings and check for multiple ethernet interfaces
+# (we have at least the mac of PXE boot in bootmac)
 if [ -n "${essid}" ] ; then
   # WLAN setup will most probably change the network interface name stored in
   # nwif (to wlan0 or something like that)
@@ -343,18 +352,35 @@ if [ -n "${essid}" ] ; then
   #/bin/ash
 else
   # check here for the active ethernet link
-  ip link show dev eth1 >/dev/null 2>&1 && error "$init_2eif" nonfatal
+  for ethif in "eth0 eth1 eth2 eth3" ; do
+    macaddr=$(ip link show dev $ethif 2>/dev/null | \
+      sed -n "/ether [0-9e-f]\{2\}:.*/p" | sed -e "s/.*ether //;s/ .*//")
+    if [ "$macaddr" = "$bootmac" ] ; then
+      nwif=$ethif
+      break
+    elif [ "x$macaddr" = "x" ] ; then
+      # if the macaddr is empty on the first interface tried, there is no
+      # network adaptor visible (missing kernel module)
+      if [ "$ethif" = "eth0" ] ; then
+        error "$init_errnwad"
+      else
+        # assume a forcedeth problem here (nonmatching MACs)
+        error "$init_nveth" nonfatal
+        macaddr=${bootmac}
+      fi
+      break
+    fi
+  done
 fi
-
-runinithook '10-have-nw-modules'
 
 # set up loopback networking
 [ $DEBUGLEVEL -eq 20 ] && echo "** starting ip config at $(sysup)"
 ip link set dev lo up
 ip addr add 127.0.0.1/8 dev lo
 ip link set dev $nwif up || error "$init_noeth"
-macaddr=$(ip link show dev $nwif|sed -n "/ether [0-9e-f]\{2\}:.*/p" \
-  |sed -e "s/.*ether //;s/ .*//")
+
+# XEN bridge config
+[ -n "$xenbr" ] && xenbr_config
 
 # analyze ip information from the kernel command line and put parts
 # of it into several variables
@@ -373,7 +399,8 @@ if [ -n "$ipinfo" ] ; then
 subnet_mask=$subnet_mask\ngateway=$gateway\nserverip=$serverip" \
     >>/etc/machine-setup
   # set static ip address
-  ip addr add $clientip/$(nm2pref $subnet_mask) dev $nwif
+  ip addr add \
+    $clientip/$(ipcalc -s -p $clientip $subnet_mask|sed s/.*=//) dev $nwif
   ip route add default via $gateway
 else
   noipyet="yes"
@@ -388,8 +415,8 @@ if [ -n "$noipyet" ] ; then
     [ -f /tmp/confviadhcp ] && . /tmp/confviadhcp
     [ -z "$clientip" -o -z "$subnet_mask" -o -z "$gateway" \
       -o -z "$broadcast_address" ] && error "$init_errdhcp"
-    ip addr add $clientip/$(nm2pref $subnet_mask) broadcast $broadcast_address \
-      dev $nwif
+    ip addr add $clientip/$(ipcalc -s -p $clientip $subnet_mask) \
+      broadcast $broadcast_address dev $nwif
     ip route add default via $gateway
   else
     if [ -n "$file" -a "$srvproto" = "lbdev" ] ; then
@@ -563,6 +590,7 @@ if [ -z "${bldmod}" -a -z "${bldhost}" -a -z "${nfsroot}" ] ; then
   # information has to be read from dhcp and ldap configuration
   cfgcomplete
 fi
+
 # mount nfs rootfs
 if [ -z "${bldmod}" -a -z "${bldserver}" ] ; then
   [ $DEBUGLEVEL -eq 20 ] && echo "** started nfs mount"
@@ -571,12 +599,14 @@ if [ -z "${bldmod}" -a -z "${bldserver}" ] ; then
   # prefer nfsserver and nfspath from kernel commandline over the information
   # gotten from dhcp server
   if [ -n "${nfsserver}" -a -n "${nfspath}" ] ; then
+    # load the nfs module if needed
+    nfsmod
     # check if nfsserver is set as variable @@@serverip@@@
     nfsserver=$(checkip $nfsserver)
     nfsroot=${nfsserver}:${nfspath}
   else
-    # the root_path should contain server ip and path in nfsroot notation
-    nfsroot=${root_path}
+    # we got a problem here
+    error "$init_nfssp" fatal
   fi
   for proto in tcp udp fail; do
     [ $proto = "fail" ] && { error "$init_nfs"; break; }
