r1048@pythagoras (orig r1047):  zooey | 2007-05-11 22:38:01 +0200  * changed the way the DB-modules are tested: now we check for the OpenSLX::MetaDB modules    instead of the DBD-drivers, as they may have additional requirements (which is the case for CSV).

diff --git a/branches/4.1.0/Makefile b/branches/4.1.0/Makefile
--- a/branches/4.1.0/Makefile
+++ b/branches/4.1.0/Makefile
@@ -130,8 +130,8 @@ install:
 		. ${SLX_CONFIG_PATH}/settings.local; \
 	fi; \
 	for m in $${SLX_DB_TYPE} SQLite CSV mysql; do \
-		if ! perl -e "use DBD::$$m" 2>>${SLX_INSTALL_LOG} ; then \
-			echo -e "  'DBD::$$m' not found, so $$m-databases will not be \
+		if ! perl -Ilib -Iconfig-db -e "use OpenSLX::MetaDB::$$m" 2>>${SLX_INSTALL_LOG} ; then \
+			echo -e "  'DBD::$$m' not found (or too buggy), so $$m-databases will not be \
 supported."; \
 		else \
 			if test "$${DEFAULT_DB_TYPE}X" = "X"; then \
