r1301@pythagoras (orig r1300):  dsuchod | 2007-08-01 19:49:08 +0200  Allow local device source for vmware/virt.machine stuff too. Removed  deprecated $imgsrv variable ...

diff --git a/trunk/initramfs/initrd-stuff/bin/servconfig b/trunk/initramfs/initrd-stuff/bin/servconfig
--- a/trunk/initramfs/initrd-stuff/bin/servconfig
+++ b/trunk/initramfs/initrd-stuff/bin/servconfig
@@ -117,13 +117,7 @@ if [ "x$vmware" != "x" ] && [ "x$vmware" != "xno" ] ; then
     pool=default
   fi
   # get source of vmware image server (get type, server and path)
-  if [ -n "${imgsrv}" ] ; then
-    vmimgprot=$(uri_token $imgsrv prot)
-    vmimgserv=$(uri_token $imgsrv server)
-    vmimgpath="$(uri_token $imgsrv path)"
-  # on DHCP config systems vmware image server might be coded into the
-  # $vmware variable
-  elif strinstr "/" "$vmware" ; then
+  if strinstr "/" "$vmware" ; then
     vmimgprot=$(uri_token $vmware prot)
     vmimgserv=$(uri_token $vmware server)
     vmimgpath="$(uri_token $vmware path)"
@@ -133,13 +127,17 @@ if [ "x$vmware" != "x" ] && [ "x$vmware" != "xno" ] ; then
   case "${vmimgsprot}" in
     *nbd)
     ;;
+    file)
+      # we expect the stuff on toplevel directory  
+      mount -o ro /dev/${vmimgserv} /mnt/var/lib/vmware || error "$scfg_evmlm"
+    ;;
     *)
-    # we expect nfs mounts here ...
-    for proto in tcp udp fail; do
-      [ $proto = "fail" ] && { error "$scfg_nfs" nonfatal; noimg=yes; break;}
-      mount -n -t nfs -o ro,nolock,$proto ${vmimgserv}:${vmimgpath} \
-        /mnt/var/lib/vmware && break
-    done
+      # we expect nfs mounts here ...
+      for proto in tcp udp fail; do
+        [ $proto = "fail" ] && { error "$scfg_nfs" nonfatal; noimg=yes; break;}
+        mount -n -t nfs -o ro,nolock,$proto ${vmimgserv}:${vmimgpath} \
+          /mnt/var/lib/vmware && break
+      done
     ;;
   esac
   # if only the path is given expect a local source within exported
@@ -244,7 +242,7 @@ if [ "x$automnt" != "xno" ] ; then
 /misc\t#/etc/auto.misc" >/mnt/etc/auto.master
       echo -e "# /etc/auto.misc - file generated by $0:\nautomount for \
 removable devices is mostly deprecated, so /misc is not\nactivated in \
-auto.master." > /mnt/etc/auto.misc
+auto.master." >/mnt/etc/auto.misc
     fi
     if [ -n "${automnt_src}" ] ; then
       # local directory and home directory server from machine-setup
