r71@pythagoras (orig r70):  fe5 | 2006-02-10 12:56:27 +0100  Neues Standardnetzwerkmodul  Distroerkennungsverbesserung  Udevfehlersuche

diff --git a/dxs/ld4/initrd/mkdxsinitrd b/dxs/ld4/initrd/mkdxsinitrd
--- a/dxs/ld4/initrd/mkdxsinitrd
+++ b/dxs/ld4/initrd/mkdxsinitrd
@@ -150,7 +150,7 @@ copy_distro_stuff() {
 #########################################################################
 # End of function declaration
 
-while getopts :hgk:i:r:o:s:f:n:Sut:d:I:V:a: a ; do
+while getopts :hgk:i:r:o:s:f:n:Sut:d:v:I:V:a: a ; do
     case $a in
 	\:|\?)	case $OPTARG in
 		k)  echo "-k requires kernel version parameter"
@@ -168,6 +168,8 @@ while getopts :hgk:i:r:o:s:f:n:Sut:d:I:V:a: a ; do
 		t)  echo "-t requires tmp dir parameter"
 		    ;;
                 d)  echo "-d requires linux distribution name"
+                    ;;
+                v)  echo "-v requires linux distribution version"
                     ;;
 		I)  echo "-I requires network interface parameter"
 		    ;;
@@ -198,6 +200,8 @@ while getopts :hgk:i:r:o:s:f:n:Sut:d:I:V:a: a ; do
 	t)  INSTDIR=$OPTARG
 	    ;;
         d)  DISTRO=$OPTARG
+            ;;
+        v)  DISTRO_VER=$OPTARG
             ;;
  	I)  NET_IF=$OPTARG
 	    ;;
@@ -250,10 +254,17 @@ if [ -z "${DISTRO}" ] ; then
   if [ -e ${ROOTDIR}/etc/SuSE-release ] ; then
     DISTRO=suse
     DISTRO_VER=`grep "VERSION" ${ROOTDIR}/etc/SuSE-release | sed "s/.*= //"`
+  elif [ -e ${ROOTDIR}/etc/lsb-release ] ; then
+    . ${ROOTDIR}/etc/lsb-release 
+    DISTRO=${DISTRIB_ID}
+    DISTRO_VER=${DISTRIB_RELEASE}
   elif [ -e ${ROOTDIR}/etc/debian_version ] ; then
     DISTRO=debian
     DISTRO_VER=`cat ${ROOTDIR}/etc/debian_version`
-  fi
+  else
+    echo "Could not detect client distribution type and version. Please specify as command line argument (-d <distro-name> -v <distro-version)"
+    exit 1;
+  fi  
 fi
 
 case "${DISTRO}" in
@@ -270,6 +281,7 @@ case "${DISTRO}" in
     case "${DISTRO_VER}" in
       Breezy*|breezy*|*)
         DISTRO_VER=5.10
+        cp ${ROOTDIR}/lib/libnss_compat.so.2 ${INSTDIR}/lib
       ;;
     esac
     ;;
@@ -297,12 +309,12 @@ case "${DISTRO}" in
       ;;
     esac
      
-    # hotplug/udev style and stuff
-    cp -a ${ROOTDIR}/etc/udev ${INSTDIR}/etc
     #cp -a /etc/sysconfig/{hardware,network}  ${INSTDIR}/etc/sysconfig
   ;;
 esac
 
+# hotplug/udev style and stuff
+cp -a ${ROOTDIR}/etc/udev ${INSTDIR}/etc
 
 # an dieser stelle sollte jetzt sichergestellt sein, dass sowohl DISTRO als auch DISTRO_VER eindeutig gesetzt sind!
 
@@ -311,8 +323,8 @@ esac
 copy_distro_stuff ${DISTRO} ${DISTRO_VER}
 
 # devices needed rather early (copied from /tmp to /dev in init)
-mknod ${INSTDIR}/tmp/console c 5 1 &>/dev/null
-mknod ${INSTDIR}/tmp/null c 1 3 &>/dev/null
+mknod ${INSTDIR}/tmp/console c 5 1 #&>/dev/null
+mknod ${INSTDIR}/tmp/null c 1 3 #&>/dev/null
 mknod ${INSTDIR}/tmp/kmsg c 1 11 &>/dev/null
 
 #if no klibc - klibc shell seems not to have enough functionality :-(
@@ -390,7 +402,7 @@ case "${DISTRO}" in
 esac
 
 # add needed libraries depending on choosen binaries
-for lib in `ldd /tmp/dxs-instrd/bin/* 2>/dev/null | sed -e "s,tls,," \
+for lib in `ldd /tmp/dxs-instrd/bin/* 2>/dev/null | sed -e "s,tls,," -e "s,i686/cmov,," \
   -ne 's:\t\(.* => \)\?\(/.*\) (0x[0-9a-f]*):\2:p' | sort -u` ; do
   baselib=`basename ${lib}`
   test -e  ${INSTDIR}/lib/${baselib} || \
@@ -411,7 +423,7 @@ if [ -z "$KERNVER" ] ; then
 fi
 
 if [ -z "$NWMODULES" ] ; then
-  NWMODULES="e100 tg3 via-rhine r8169"
+  NWMODULES="e100 tg3 via-rhine r8169 pcnet32"
 fi
 if [ -z "$FSMODULES" ] ; then
   FSMODULES="nbd nfs"
