r600@pythagoras (orig r599):  lmuelle | 2007-01-07 23:01:41 +0100  Add SLX_BOOTSTRAP_FAIL_WGET.  This allows us to tolerate failing wget  calls in the bootstrap environment.
 This is required as the SUSE Linux 10.1 exits in two different flavors.
 The Genral Availability (GA) and the remastert version.
 
 Till now we did all testing with the remastered CDs.  Therefore we
 failed as soon as we tired to use the version available from
 openSUSE.org.

diff --git a/trunk/installer/slxbootstrap b/trunk/installer/slxbootstrap
--- a/trunk/installer/slxbootstrap
+++ b/trunk/installer/slxbootstrap
@@ -2,6 +2,7 @@
 
 PATH="/bin:/sbin:/usr/bin:/usr/sbin"
 
+: ${SLX_BOOTSTRAP_FAIL_WGET:="yes"}
 : ${SLX_BOOTSTRAP_PATH:="/slxbootstrap"}
 : ${SLX_STAGE1_FINAL_PATH:="/slxfinal"}
 
@@ -24,8 +25,12 @@ cd "${SLX_BOOTSTRAP_PATH}"
 for file in ${SLX_BASE_PREREQ_PACKAGES}; do
 	wget "${SLX_INST_SOURCE_BASEURL}${SLX_INST_SOURCE_PACKAGE_SUBDIR:+/${SLX_INST_SOURCE_PACKAGE_SUBDIR}}/${file}"
 	if test $? != 0; then
-		echo "Error: Unable to download ${SLX_INST_SOURCE_BASEURL}/${file}"
-		exit 1
+		if test "${SLX_BOOTSTRAP_FAIL_WGET}" = "no"; then
+			continue
+		else
+			echo "Error: Unable to download ${SLX_INST_SOURCE_BASEURL}/${file}"
+			exit 1
+		fi
 	fi
 	case "${file}" in
 		*.deb)
@@ -51,7 +56,7 @@ done
 
 for file in ${SLX_BASE_BOOTSTRAP_PACKAGES}; do
 	wget "${SLX_INST_SOURCE_BASEURL}${SLX_INST_SOURCE_PACKAGE_SUBDIR:+/${SLX_INST_SOURCE_PACKAGE_SUBDIR}}/${file}"
-	if test $? != 0; then
+	if test $? != 0 -a "${SLX_BOOTSTRAP_FAIL_WGET}" = "yes"; then
 		echo "Error: Unable to download ${SLX_INST_SOURCE_BASEURL}/${file}"
 		exit 1
 	fi
