r2296@pythagoras (orig r2295):  schmelzs | 2008-10-14 19:20:22 +0200   * fix for #212

diff --git a/openslx/trunk/initramfs/stage3-stuff/init b/openslx/trunk/initramfs/stage3-stuff/init
--- a/openslx/trunk/initramfs/stage3-stuff/init
+++ b/openslx/trunk/initramfs/stage3-stuff/init
@@ -875,10 +875,17 @@ else
     for plugin_starter in /etc/plugin-init.d/*.sh; do
       if [ -e $plugin_starter ]; then
         [ $DEBUGLEVEL -gt 0 ] \
-          && echo "Running plugin starter $plugin_starter ..."
+          && echo -n "Running plugin starter $plugin_starter ..."
         [ $DEBUGLEVEL -eq 15 ] \
           && sed '/^#!/ a\\set -x' -i $plugin_starter
-        . $plugin_starter >>/tmp/plugin_starter 2>&1
+          init-wrapper $plugin_starter >>/tmp/plugin_starter 2>&1
+          if [ $? -eq 0 ]; then
+            [ $DEBUGLEVEL -gt 0 ] \
+            && echo " ok"
+          else
+            [ $DEBUGLEVEL -gt 0 ] \
+            && echo " failed"
+          fi
       fi
     done
   fi
