r1609@pythagoras (orig r1608):  zooey | 2008-03-06 20:55:59 +0100  * added check for rsync, as we rely on it being installed

diff --git a/openslx/trunk/Makefile b/openslx/trunk/Makefile
--- a/openslx/trunk/Makefile
+++ b/openslx/trunk/Makefile
@@ -129,6 +129,10 @@ supported."; \
 	else \
 		echo $${DEFAULT_DB_TYPE} >DEFAULT-DB-TYPE; \
 	fi; \
+	if ! which rsync >/dev/null 2>&1; then \
+		echo "  rsync is required, please install it."; \
+		exit 1; \
+	fi; \
 	echo "Installing OpenSLX project files"; \
 	mkdir -p $(SLX_BUILD_PATH)$(SLX_CONFIG_PATH) \
 	      -p $(SLX_BUILD_PATH)$(SLX_BASE_PATH)/lib \
