r1125@pythagoras (orig r1124):  dsuchod | 2007-05-31 21:34:06 +0200  Change in pcitable (see #100) eepro100 -> e100. Changeback of silly  comments in mkdxsinitrd.

diff --git a/trunk/initramfs/mkdxsinitrd b/trunk/initramfs/mkdxsinitrd
--- a/trunk/initramfs/mkdxsinitrd
+++ b/trunk/initramfs/mkdxsinitrd
@@ -101,18 +101,17 @@ precheck() {
     echo -e "\nYou don't have the needed permission. Please rerun as root user!\n"
     exit 1
   fi
-  # fixme:: Do we really need this!?
   # Check for correct settings of SLX-Variables
-  #if [ "x" == "x$SLX_BASE_PATH" ]; then
-  #  if [ "x$SLX_CONFIG_PATH" == "x@@@SLX_CONFIG_PATH@@@" ]; then
-  #     echo "Please make sure you install the Open SLX Software properly,"
-  #     echo "i.e. install it using the provided Makefile. Thanks."
-  #  else
-  #     echo "Essential configuration is missing. Please verify"
-  #     echo "existence and correctness of $SLX_SHARE_PATH/settings.default"
-  #  fi
-  #  exit 1
-  #fi
+  if [ "x" == "x$SLX_BASE_PATH" ]; then
+    if [ "x$SLX_CONFIG_PATH" == "x@@@SLX_CONFIG_PATH@@@" ]; then
+       echo "Please make sure you install the Open SLX Software properly,"
+       echo "i.e. install it using the provided Makefile. Thanks."
+    else
+       echo "Essential configuration is missing. Please verify"
+       echo "existence and correctness of $SLX_SHARE_PATH/settings.default"
+    fi
+    exit 1
+  fi
 }
 
 # replaces which command to find executables inside ROOTDIR
